branch-defaults:
  master:
    environment: Vlivenextjs-prod
environment-defaults:
  Vlivenextjs-prod:
    branch: null
    repository: null
global:
  application_name: vlive-nextjs
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
